---
- name: Ensure fail2ban installed
  package:
    name: fail2ban
    state: present

- name: Configure fail2ban jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart fail2ban

- name: Ensure fail2ban running
  systemd:
    name: fail2ban
    enabled: true
    state: started
