---
- name: Restart sshd
  service:
    name: ssh
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: Restart auditd
  service:
    name: auditd
    state: restarted
  when:
    - ansible_service_mgr == 'systemd'
    - not ansible_check_mode | default(false)

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when:
    - ansible_service_mgr == 'systemd'
    - not ansible_check_mode | default(false)
