---
- name: Deploy monitoring stack
  hosts: monitoring_hosts
  become: true
  gather_facts: true
  serial: 1

  pre_tasks:
    - name: Ensure Docker dependencies are present
      import_role:
        name: docker
      tags: [docker]

    - name: Install Python packages for Docker SDK
      package:
        name: python3-pip
        state: present
      tags: [docker]

    - name: Install Docker SDK for Python
      pip:
        name:
          - docker
          - docker-compose
        state: present
      tags: [docker]

  roles:
    - role: monitoring
      tags: [monitoring]

  post_tasks:
    - name: Wait for Grafana API to respond
      uri:
        url: http://localhost:3000/api/health
        status_code: 200
        validate_certs: false
      register: grafana_health
      retries: 10
      delay: 12
      until: grafana_health.status == 200
      tags: [verification]

    - name: Show monitoring endpoints
      debug:
        msg:
          - "Prometheus: http://{{ ansible_default_ipv4.address | default('localhost') }}:9090"
          - "Grafana: http://{{ ansible_default_ipv4.address | default('localhost') }}:3000"
          - "Alertmanager: http://{{ ansible_default_ipv4.address | default('localhost') }}:9093"
      tags: [verification]
