---
- name: Install and configure Zabbix agent
  hosts: zabbix_agent_hosts
  become: true
  gather_facts: true
  serial: 5

  roles:
    - role: zabbix_agent
      tags: [zabbix, agent]

  post_tasks:
    - name: Display agent registration info
      debug:
        msg:
          - "Agent hostname: {{ zabbix_agent_hostname }}"
          - "Listening port: {{ zabbix_agent_listen_port }}"
          - "Server(s): {{ zabbix_agent_server }}"
